import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Test App Unicorn",
  description: "Generated by Next.JS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <header className="flex h-12 items-center bg-white text-black pl-20 shadow-2xl">
          <h1 className="text-md font-bold">App title</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
